before_script:
  - npm install -g grunt-cli
  - git submodule update --init --recursive
env:
  global:
    ## SAUCE_USERNAME kites-opensauce
    - secure: 'S4wilT+YiqG+zCwLJ6XHEdbot8xdjuZ9TMkL1t0nfO8DzDqalwXii80hL0CrHOEkKUDvj6RHRgS/DZNlJmWGxsUT3r2dShzZcyRYS8pm4uuBGyb52lZqnBEB0//gnWoV4XmTmGjiLF0YeB6y6V3vRxU174+1JmEXYa063cToG6Q='
    - secure: 'Ofw0dpSd9/BQYgMC4WInlzn4yRZv9yyGY8nv9kW2vcb/kNCo5KpzX7sXJSP9Rcmx7fp3bXVBXDGgD46i9F8bsh2Zpzd8gqOoq1Gg/S8pzENy/h93Na5MZ3J4jk0g93fmMrb+hMm0b/DOKzco7w8V/uoE9nKn8YpRiqJtqRg3w2o='
language: node_js
node_js:
  - 0.10
