before_script:
  - npm install -g grunt-cli
  - git submodule update --init --recursive
env:
  global:
    - secure: 'AaRHoLIODuSG8V1nJepdnu/SdYDrFAblki8+otpeErR789jZA8aEqSWLZN84Yq0Yf5i6hn5lWkI7rC/5KCCu/OfKgFu7VJy3gVTro7jml8XX6I3bEFBx8erHRV+dH4l5zoIzTvlrzUUF+P8A2AacvVfD2qjczQEPRa8tUUoM4tE='
    - secure: 'QX6mTTgMgFsI1nV/VNBnfbUoeHOzJmUmzGCXvOC58g24Wp4FhS/e3MpBhi96L+eVuJ5B35qq979QpxIHwyro/q2JGjJl45yRsiInCE0SV6f+jncnOmp6M/vAASqeRnbPHs6EleANs+NFOET8+oxvzPnLXCsJxfq1qp9t3igdVrw='
language: node_js
node_js:
  - 0.10
