ui: mocha-qunit
## https://saucelabs.com/platforms
## https://saucelabs.com/rest/v1/info/browsers/webdriver
browsers:
  - name: android
    version: latest
  - name: firefox
    version: 25..latest
  - name: chrome
    version: 30..latest
  - name: ie
    version: 10..latest
  - name: iphone
    version: 5..latest
  - name: safari
    version: 6..latest
